# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161215_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
