# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 18:18
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161215_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=app.models.get_date_end),
        ),
    ]
