# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161216_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
