# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_listdevices'),
    ]

    operations = [
        migrations.AddField(
            model_name='listdevices',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
