# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_listdevices_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['status', 'id']},
        ),
    ]
